### ISSUE TITLE
reset timer when user manually advances slide

### ISSUE THREAD

**Issue by leemark** [leemark/better-simple-slideshow#6]

**Comment by blk4rd** [comment]
Quite a bit late, I see, but this would be quite helpful to implement in my case.  Any word on if this is being looked at/worked on?

**Comment by tonystark93** [comment]
@blk4rd It can be implemented to reset the slider. (reset the slider means further slide movement will be Stopped, am I right?)

**Comment by blk4rd** [comment]
I want the speed variable to be reset when the slide is manually advanced.  Currently, with a 5 second timer, one can wait 3 seconds, advance to the next slide, and only get 2 seconds before the slide is advanced automatically.  The timer itself does not reset to the original 5 seconds when somebody uses the manual controls.
